name: Module CI

on:
  push:
  pull_request:

env:
  OAI_API_ADMIN_EMAIL: info@test.com

jobs:
  ci:
    uses: silverstripe/github-actions-ci-cd/.github/workflows/ci.yml@0.1.15
    with:
      default_jobs: |
        - php: 7.4
          phpcoverage: true
        - php: 7.4
          phplinting: true
        - php: 7.4
          phpunit: true
        - php: 8.0
          phpunit: true
